# Change these first
owner: lovelygfj # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Glitch
    url: https://utopian-titanium-rain.glitch.me/
  - name: Glitch1
    url: https://brook-amethyst-arrow.glitch.me/
  - name: Glitch1
    url: https://lively-pitch-runner.glitch.me/   
  - name: Replit_US
    url: https://9931e56a-5708-4f5b-9106-c12a7dffbeeb-00-bz5t6i25ixe2.worf.replit.dev/
  - name: Replit_IN
    url: https://15fbe78e-95f8-4704-92ef-ee3b56173e2f-00-2skk1g476w4as.sisko.replit.dev/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status_Check
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
